/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_openzl_OpenZLJNI */

#ifndef _Included_net_openzl_OpenZLJNI
#define _Included_net_openzl_OpenZLJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    nativeInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_openzl_OpenZLJNI_nativeInit
  (JNIEnv *, jclass);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    nativeShutdown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_net_openzl_OpenZLJNI_nativeShutdown
  (JNIEnv *, jclass);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    createCompressor
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_net_openzl_OpenZLJNI_createCompressor
  (JNIEnv *, jclass, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    destroyCompressor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_openzl_OpenZLJNI_destroyCompressor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    createDecompressor
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_net_openzl_OpenZLJNI_createDecompressor
  (JNIEnv *, jclass);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    destroyDecompressor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_net_openzl_OpenZLJNI_destroyDecompressor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressSerial
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressSerial
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressSerialToBuffer
 * Signature: (J[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_net_openzl_OpenZLJNI_compressSerialToBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressNumeric
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressNumeric
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressNumericInts
 * Signature: (J[I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressNumericInts
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressNumericLongs
 * Signature: (J[J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressNumericLongs
  (JNIEnv *, jclass, jlong, jlongArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressNumericFloats
 * Signature: (J[F)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressNumericFloats
  (JNIEnv *, jclass, jlong, jfloatArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressNumericDoubles
 * Signature: (J[D)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_compressNumericDoubles
  (JNIEnv *, jclass, jlong, jdoubleArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressSerial
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_decompressSerial
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressSerialToBuffer
 * Signature: (J[BII[BII)I
 */
JNIEXPORT jint JNICALL Java_net_openzl_OpenZLJNI_decompressSerialToBuffer
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressNumeric
 * Signature: (J[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_net_openzl_OpenZLJNI_decompressNumeric
  (JNIEnv *, jclass, jlong, jbyteArray, jint, jint);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressNumericInts
 * Signature: (J[B)[I
 */
JNIEXPORT jintArray JNICALL Java_net_openzl_OpenZLJNI_decompressNumericInts
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressNumericLongs
 * Signature: (J[B)[J
 */
JNIEXPORT jlongArray JNICALL Java_net_openzl_OpenZLJNI_decompressNumericLongs
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressNumericFloats
 * Signature: (J[B)[F
 */
JNIEXPORT jfloatArray JNICALL Java_net_openzl_OpenZLJNI_decompressNumericFloats
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    decompressNumericDoubles
 * Signature: (J[B)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_openzl_OpenZLJNI_decompressNumericDoubles
  (JNIEnv *, jclass, jlong, jbyteArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    getCompressionInfo
 * Signature: ([B)Lnet/openzl/CompressionInfo;
 */
JNIEXPORT jobject JNICALL Java_net_openzl_OpenZLJNI_getCompressionInfo
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     net_openzl_OpenZLJNI
 * Method:    compressBound
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_net_openzl_OpenZLJNI_compressBound
  (JNIEnv *, jclass, jint);


#ifdef __cplusplus
}
#endif
#endif
